name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  # Or your default branch
jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PythonAnywhere CLI
      run: pip install pythonanywhere

    - name: Update frontend files on PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USER: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        pa_update_files.py \
          --python=3.8 \
          --repo_url https://github.com/${{ github.repository }}.git \
          --repo_dir / \
          --target_dir /home/$PA_USER/mysite/frontend/RPG
