name: Deploy to PythonAnywhere

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
      
      - name: Copy repository to PythonAnywhere
        run: rsync -avz --exclude '.git' ./ ${{ secrets.PA_USER }}@ssh.pythonanywhere.com:/home/${{ secrets.PA_USER }}/path/to/repository/
        env:
          PA_USER: your_pythonanywhere_username
