name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  # Or your default branch
jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create tarball of frontend files
      run: |
        mkdir -p temp_frontend
        shopt -s extglob
        cp -R !(temp_frontend) temp_frontend/ || true
        tar -czf frontend.tar.gz -C temp_frontend .

    - name: Upload files to PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USER: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        curl -X POST \
        -H "Authorization: Token $PA_TOKEN" \
        -F "content=@frontend.tar.gz" \
        https://www.pythonanywhere.com/api/v0/user/$PA_USER/files/path/home/$PA_USER/mysite/frontend/RPG/frontend.tar.gz

    - name: Extract files on PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USER: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # First, create a new Bash console
        CONSOLE_ID=$(curl -X POST \
          -H "Authorization: Token $PA_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"executable": "bash"}' \
          https://www.pythonanywhere.com/api/v0/user/$PA_USER/consoles/ \
          | jq -r '.id')
        
        # Then, send the command to the console
        curl -X POST \
          -H "Authorization: Token $PA_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "input": "cd /home/'$PA_USER'/mysite/frontend/RPG && tar -xzf frontend.tar.gz"
          }' \
          https://www.pythonanywhere.com/api/v0/user/$PA_USER/consoles/$CONSOLE_ID/send_input/
