name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  # Or your default branch
jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust this to match your PythonAnywhere Python version

    - name: Install PythonAnywhere CLI
      run: |
        python -m pip install --upgrade pip
        pip install pythonanywhere

    - name: Update frontend files on PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USER: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        python -m pythonanywhere.pa_update_files \
          --python=3.8 \
          --repo_url https://github.com/${{ github.repository }}.git \
          --repo_dir / \
          --target_dir /home/$PA_USER/mysite/frontend/RPG
